<?php

/**
 * @file bellcom_eim.module file
 */

/**
 * Implements hook_field_widget_WIDGET_TYPE_form_alter().
 *
 * Add a #process callback to the imagefield widget element so we
 * can perform alters.
 * See http://drupal.org/node/887424
 */
function bellcom_eim_field_widget_media_generic_form_alter(&$element, &$form_state, $context) {
  foreach (element_children($element) as $delta){
    $element[$delta]['#process'][] = 'eim_imagefield_widget_process';
  }
}
